// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace CSharpT4Samples.T4
{
    [StructLayout(LayoutKind.Sequential, Size = 6 * 32 /*bytes * items*/)]
    readonly struct PlineApexs
    {
        public readonly ApexAtsv x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, x29, x30, x31;

        public int Length => 32;
        public ApexAtsv this[int i]
        {
            get
            {
                if (i >= Length) throw new IndexOutOfRangeException();
                return i switch
                {
                    0 => x0,
1 => x1,
2 => x2,
3 => x3,
4 => x4,
5 => x5,
6 => x6,
7 => x7,
8 => x8,
9 => x9,
10 => x10,
11 => x11,
12 => x12,
13 => x13,
14 => x14,
15 => x15,
16 => x16,
17 => x17,
18 => x18,
19 => x19,
20 => x20,
21 => x21,
22 => x22,
23 => x23,
24 => x24,
25 => x25,
26 => x26,
27 => x27,
28 => x28,
29 => x29,
30 => x30,
31 => x31,
                    _ => throw new NotImplementedException()
                };
            }
        }

        public IEnumerator<ApexAtsv> GetEnumerator()
        {
            for (int i = 0; i < Length; ++i)
                yield return this[i];
        }
    }

}
